### ISSUE TITLE
Implement keyboard shortcuts for 3 actions

### ISSUE THREAD

**Issue by emilykangdev** [Husky-Coding-Project/calendar#14]
## Problem/context: 
- We want the calendar to be intuitive, and not depend too much on clicking. 
- Much of the calendar is already handled from the calendar library, so ideally we implement keyboard shortcuts from scratch or with as few modules as possible. 
- These actions can be anything, like event creation, opening the settings page (if we have one by this point), closing the app, etc.

## Time expected, skills , # people:
- 3h+. 
- Solid JS knowledge of event listeners and you'll have to know how to call methods from the calendar library. 
- 1-2 frontend people. Or all 3. 

## Tasks: 
- EASY AND ALREADY DONE: Do a super mini-project: when a user presses a key, print what key they pressed just for a few keys.
- DONE-ISH: Figure out the structure of your code. 
    - just link an external "keyboardshortcuts.js" file in the HTML and make changes there! 
- Choose your 3 actions and code them in. Can be hard-coded shortcuts for now. Allowing the user to change shortcuts is for a future issue: 

- [ ] Event creation on the selected day 
- [ ] Let the user use arrow keys to navigate to other days! (HARDER)
- [ ] Open settings (DONE)
